config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :islands, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  mount_uploader :phototwo, PhotoUploader
  mount_uploader :photothree, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :island

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :island
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservations
  has_many :islands
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         # :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?



def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def show
    @island = Island.find(params[:id])
    @marker =
      {
        lat: @island.latitude,
        lng: @island.longitude
      }
    @reservation = Reservation.new
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(set_params)
    @island.user = current_user
    if @island.save
      redirect_to island_path(@island)
    else
      render :new
    end
  end

  def edit
    @island = Island.find(params[:id])
  end

  def update
    @island = Island.find(params[:id])
    @island.update(set_params)
    redirect_to islands_path
  end

  def destroy
  @island = Island.find(params[:id])
  @island.destroy
  redirect_to reservations_path
end


  private

  def set_params
    params.require(:island).permit(:name, :location, :description, :booked, :photo, :phototwo, :photothree, :price_by_night)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    if params[:query].present?
      @islands = Island.where(name: params[:query])
    elsif
      @islands = Island.geocoded #returns flats with coordinates
      @markers = @islands.map do |island|
        {
          lat: island.latitude,
          lng: island.longitude
        }
      end
    else
      @islands = Island.all
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

def index
  @user = current_user
  @reservations = Reservation.all
end

def show
  @reservation = Reservation.find(params[:id])
  @island = @reservation.island
  @price_by_night = @island.price_by_night
end

def new
  @reservation = Reservation.new
  @island = Island.find(params[:island_id])
  @reservation.island = @island
end

def create
  @reservation = Reservation.new(params_reservation)
  @reservation.user = current_user
  @reservation.island = Island.find(params[:island_id])

  if @reservation.save
    redirect_to reservation_path(@reservation)
  else
    render :new
  end
end

def destroy
  @reservation = Reservation.find(params[:id])
  @reservation.destroy
  redirect_to reservations_path
end

private
  def params_reservation
    params.require(:reservation).permit(:starting_date, :ending_date, :island_id, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/islands/edit.html.erb
<div class="container mt-4">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="-form">
          <h1>Edit this Island</h1>
          <div class="mt-3">
            <%= simple_form_for(@island) do |f| %>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :location %>
                <%= f.text_field :location, class: 'form-control' %>
              </div>
               <div class="form-group">
                <%= f.label :description %>
                <%= f.text_field :description, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :price_by_night %>
                <%= f.text_field :price_by_night, class: 'form-control' %>
              </div>
              <div class="mt-3">
                <%= f.submit class: 'btn btn-primary' %>
                <%= link_to 'Cancel', islands_path, class: 'btn btn-danger ml-2' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/islands/new.html.erb
  <div class="main-container">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="-form ">
          <div class="mt-3 ">
            <%= simple_form_for(@island) do |f| %>
              <h1>Add a new Island 🏝️</h1>
              <div class="form-group">
                <%= f.label :name, label: "Enter your Island name:" %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :location, label: "Enter the location:" %>
                <%= f.text_field :location, class: 'form-control' %>
              </div>
                <div class="form-group">
                <%= f.label :description, label: "Enter a nice description:" %>
                <%= f.text_field :description, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :price_by_night, label: "Enter the price per night: €" %>
                <%= f.text_field :price_by_night, class: 'form-control' %>
              </div>
                <br>
                <div class="form-group">
                  <%= f.label :description, label: "Upload up to 3 pictures:" %>
                  <%= f.input :photo, label: "Add a picture" %>
                  <%= f.input :phototwo, as: :file, label: "Add a picture" %>
                  <%= f.input :photothree, as: :file, label: "Add a picture" %>
                </div>
              <div class="mt-3">
                <%= f.submit class: 'btn btn-secondary' %>
                <%= link_to 'Cancel', root_path(anchor: "recommandations"), class: 'btn btn-dark ml-2' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/islands/show.html.erb
<div class="main-container ">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" >
      <div class="carousel-item active">
        <img class="d-block w-80" alt=" Image not uploaded" src=<%= @island.photo %> >
      </div>
      <% if @island.phototwo == true %>
      <div class="carousel-item ">
        <img class="d-block w-80" alt=" Image not uploaded" src=<%= @island.phototwo %> >
      </div>
      <% else %>
        <div class="carousel-item ">
          <img class="d-block w-80" alt=" Image not uploaded" src=<%= @island.photo %> >
        </div>
      <% end %>

      <% if @island.photothree == true %>
        <div class="carousel-item ">
          <img class="d-block w-80" alt=" Image not uploaded" src=<%= @island.photothree %> >
          </div>
      <% else %>
        <div class="carousel-item ">
          <img class="d-block w-80" alt=" Image not uploaded" src=<%= @island.photo %> >
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-7">
    <h1><%= @island.name %></h1>
    <h2><%= @island.location %></h2>
    <h2><%= @island.price_by_night %> € per night </h2>
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/ok-gaetan", class: "avatar-position avatar-bordered", alt: "avatar-position" %>
    </div>
    <div class="col-7">
        <p> <%= @island.description %>  </p>
        <p class="mt-5">
          <div
          id="map"
          style="width: 100%;
          height: 400px;"
          data-markers="<%= @marker.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        >
          </div>
        </p>
    </div>


    <div class="col-5">
      <%= simple_form_for [@island, @reservation] do |f| %>
        <%= f.input :starting_date, as: :string, required: true, input_html: {class: "datepicker"} %>
        <%= f.input :ending_date, as: :string, required: true, input_html: {class: "datepicker"} %>
        <%= f.button :submit, "Book this island 🏝️", class: "btn btn-dark btn-lg btn-block" %>
      <% end %>
  </div>
  <%= link_to 'Back to islands', root_path, class: 'btn btn-dark ml-2 mb-5' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>PALM</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all'%>
   <!--  <#%= stylesheet_pack_tag 'application' %> -->
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.css' rel='stylesheet' />

  </head>
  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= render 'shared/footer' %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container d-flex justify-content-center">
  <h3><span id="banner-typed-text" style="color: white"></span> </h3>
  </div>
  <div class="container d-flex justify-content-center">
  <a href="#recommandations" class="btn btn-outline-light btn-lg">Book an island🏝️</a>
  </div>
</div>
<div class="main-container .ml-md-3 .ml-lg-0">
  <h1 class="text-center">Our recommandations</h1>
  <%= form_tag root_path, method: :get do %>
    <div id="search-bar" class= "d-flex justify-content-center mt-5 mb-5">
      <div>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find an island"
      %>
      </div>
      <div>
        <%= submit_tag "Search", class: "btn btn-primary search-button" %>
      </div>
    </div>
  <% end %>

  <div id ="recommandations" class=" d-flex flex-wrap justify-content-center">
    <% @islands.each do |island| %>
      <%= link_to island_path(island) do %>
        <div class="card-trip">
            <img src= <%= island.photo %> >
            <div class="card-trip-infos">
              <div>
                <h2><%= island.name %></h2>
                <p><%= island.location %></p>
              </div>
              <h2 class="card-trip-pricing"> <%= island.price_by_night %>€ / night </h2>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div
  id="map"
  style="width: 100%;
  height: 500px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/reservations/index.html.erb
<div class="main-container p-4" >
<ul class="list-inline tabs-underlined">
  <li>
      <a href="#" id="reservations_btn" class="tab-underlined active">Bookings</a>
  </li>
  <li>
      <a href="#" id="islands_btn"class="tab-underlined">My Islands</a>
  </li>
</ul>
  <div id="reservations">
    <div class=" text-center d-flex flex-column align-items-center">
      <h1 class="mb-5">My reservations</h1>
      <% if @user.reservations == [] %>
        <p>You don't have any reservation.</p>
        <p class="mt-5 text-center"><%= link_to "Add a new reservation", root_path(anchor: "recommandations") %></p>
      <% else %>
        <% @user.reservations.each do |reservation| %>
          <div class="card-product">
          <img src=<%= reservation.island.photo %> />
              <div class="card-product-infos">
              <h3> <%= reservation.island.name %></h3>
              <p>Check in on: <%= reservation.starting_date %></p>
              <p>Ckeck out on: <%= reservation.ending_date %></p>
              <p> Total price: <%= (DateTime.parse(reservation.ending_date).to_i - DateTime.parse(reservation.starting_date).to_i).fdiv(3600)*reservation.island.price_by_night %> €</p>
              <p>Waiting for confirmation by <%= reservation.island.user.first_name %></p>
              <p><%= link_to "Delete this reservation 🙊", reservation_path(reservation),
          method: :delete,
          data: { confirm: "Are you sure?" } %></p>
              </div>
          </div>
        <% end %>
        <p class="mt-5 text-center"><%= link_to "Add another reservation", root_path(anchor: "recommandations") %></p>
      <% end %>
    </div>
  </div>



 <div id="my_islands" class="disapear">
    <div class=" text-center d-flex flex-column align-items-center">
      <h1 class="mb-5">My islands</h1>
      <% if @user.islands == [] %>
        <p>You currently don't host any island.</p>
        <p class="mt-3"> <%=  link_to "Add your island", new_island_path %> </p>
      <% else %>
        <% @user.islands.each do |island| %>
          <div class="card-product">
            <img src=<%= island.photo %> />
            <div class="card-product-infos">
              <h3><%= island.name %></h3>
              <p>location: <%= island.location %></p>
              <p>price: <%= island.price_by_night %>€/night</p>
              <% if island.booked == false %>
                <p>status: available</p>
              <% else %>
                <p>status: rented</p>
              <% end %>
              <p><%= link_to "Stop hosting this island", island_path(island),
                method: :delete,
                data: { confirm: "Are you sure?" } %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="main-container p-4" >
  <div class="card mx-auto bg-light mb-3" style="width: 35rem;">
    <div class="card-header text-center">
      <h4> Thank you for your reservation 🌴🍓  </h4>
    </div>

      <div class="card-body d-flex flex-column justify-content-center align-items-center border-top">
        <h4 class="card-title text-muted"> <em> Some information about your trip : </em> </h4>
        <p class="card-text text-muted"> Reservation Number : <%= @reservation.id %> </p>
        <p class="card-text text-muted"> Starting date :  <%= @reservation.starting_date %> </p>
        <p class="card-text text-muted"> Ending date :  <%= @reservation.ending_date %> </p>
        <p class="card-text text-muted"> Total price: <%= (DateTime.parse(@reservation.ending_date).to_i - DateTime.parse(@reservation.starting_date).to_i).fdiv(3600)*@island.price_by_night %> €</p>
        <div class ="d-flex align-items-center">
          <p class="mr-3"><%= link_to "Back to the home page", root_path, class: "btn btn-outline-dark " %></p>
          <p class="ml-3"><%= link_to "My reservations", reservations_path, class: "btn btn-outline-dark" %></p>
        </div>
      </div>
</div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer container border-top pt-5">
  <div class="footer-top d-flex justify-content-between align-items-start border-bottom pb-3">
    <div class="category">
      <p>Palm</p>
      <li><a href="">Careers</a></li>
      <li><a href="">News</a></li>
      <li><a href="">Policies</a></li>
      <li><a href="">Help</a></li>
      <li><a href="">Diversity & Belonging</a></li>
    </div>
    <div class="category">
      <p>Discover</p>
      <li><a href="">Trust & Safety</a></li>
      <li><a href="">Gift cards</a></li>
      <li><a href="">Palm Citizen</a></li>
      <li><a href="">Business Travel</a></li>
      <li><a href="">Guidebooks</a></li>
    </div>
    <div class="category">
      <p>Hosting</p>
      <li><a href="">Why Host</a></li>
      <li><a href="">Hospitality</a></li>
      <li><a href="">Responsible Hosting</a></li>
      <li><a href="">Community Center</a></li>
      <li><a href="">Open Homes</a></li>
    </div>
    <div class="category">
      <div class="footer-icons">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
      </div>
      <li><a href="">Terms</a></li>
      <li><a href="">Privacy</a></li>
      <li><a href="">Site Map</a></li>
    </div>
  </div>
  <div class="footer-bottom text-center mt-3">
    <p>&copy 2019 Palm, Inc. All rights reserved.</p>
  </div>
</div>

app/views/shared/_islands_list.html.erb
<div class=" d-flex flex-wrap justify-content-center">
  <% @islands.each do |island| %>
    <%= link_to island_path(island) do %>
      <div class="card-trip">
          <img src= <%= island.photo %> >
          <div class="card-trip-infos">
            <div>
              <h2><%= island.name %></h2>
              <p><%= island.location %></p>
            </div>
            <h2 class="card-trip-pricing"> <%= island.price_by_night %>€ / night </h2>
          </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-palm">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dovu27lye/image/upload/v1566228419/Palm_Logo_3_rmsnrn.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     <%#= Afficher l'avatar si user est connecté %>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%=link_to "Host your island 🌴", new_island_path, class: "nav-link mt-2" %>
        </li>
        <li class="nav-item active">
          <%= link_to current_user.first_name, reservations_path, class: "nav-link mt-2" %>

        <li class="nav-item dropdown">
          <% if current_user.avatar.nil? %>
            <%= image_tag "https://res.cloudinary.com/dovu27lye/image/upload/v1566301646/Palm_logo_2_msftzl.png", alt: "alttext", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>